import { Container, Header } from "@/components/shared";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "DodoPizza | Корзина",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#f4f1ee]">
      <Container>
        <Header hasSearch={false} hasCart={false} />
        {children}
      </Container>
    </main>
  );
}
